const DATA={
  "Person":[{de:"Name",art:"der",en:"name",lvl:"A1",phrases:[["Wie ist dein Name?","What is your name?"],["Mein Name ist Maria.","My name is Maria."]]},{de:"Adresse",art:"die",en:"address",lvl:"A1",phrases:[["Wie ist deine Adresse?","What is your address?"],["Das ist meine Adresse.","That is my address."]]},{de:"Telefon",art:"das",en:"telephone",lvl:"A1",phrases:[["Ich habe ein Telefon.","I have a phone."],["Das Telefon klingelt.","The phone rings."]]},{de:"Alter",art:"das",en:"age",lvl:"A1",phrases:[["Wie alt bist du?","How old are you?"],["Mein Alter ist 25.","My age is 25."]]},{de:"Familie",art:"die",en:"family",lvl:"A1",phrases:[["Meine Familie ist groß.","My family is big."],["Hast du Familie?","Do you have family?"]]},{de:"Freund",art:"der",en:"friend",lvl:"A1",phrases:[["Er ist mein Freund.","He is my friend."],["Ich habe einen Freund.","I have a friend."]]},{de:"Kind",art:"das",en:"child",lvl:"A1",phrases:[["Das Kind spielt.","The child plays."],["Sie hat ein Kind.","She has a child."]]},{de:"Mann",art:"der",en:"man",lvl:"A1",phrases:[["Der Mann ist alt.","The man is old."],["Da ist ein Mann.","There is a man."]]},{de:"Frau",art:"die",en:"woman",lvl:"A1",phrases:[["Die Frau ist nett.","The woman is nice."],["Eine Frau wartet.","A woman waits."]]},{de:"Aussehen",art:"das",en:"appearance",lvl:"A2",phrases:[["Sein Aussehen ist gut.","His appearance is good."],["Das Aussehen zählt nicht.","Appearance doesn't count."]]},{de:"Charakter",art:"der",en:"character",lvl:"A2",phrases:[["Er hat guten Charakter.","He has good character."],["Ihr Charakter ist stark.","Her character is strong."]]},{de:"Gefühl",art:"das",en:"feeling",lvl:"A2",phrases:[["Das ist ein gutes Gefühl.","That is a good feeling."],["Ich habe ein Gefühl.","I have a feeling."]]}],
  "Familie":[{de:"Mutter",art:"die",en:"mother",lvl:"A1",phrases:[["Meine Mutter ist nett.","My mother is nice."],["Die Mutter kocht.","The mother cooks."]]},{de:"Vater",art:"der",en:"father",lvl:"A1",phrases:[["Mein Vater arbeitet.","My father works."],["Der Vater ist groß.","The father is tall."]]},{de:"Bruder",art:"der",en:"brother",lvl:"A1",phrases:[["Mein Bruder ist jung.","My brother is young."],["Ich habe einen Bruder.","I have a brother."]]},{de:"Schwester",art:"die",en:"sister",lvl:"A1",phrases:[["Meine Schwester lacht.","My sister laughs."],["Sie ist meine Schwester.","She is my sister."]]},{de:"Sohn",art:"der",en:"son",lvl:"A1",phrases:[["Ihr Sohn ist klein.","Her son is small."],["Das ist mein Sohn.","This is my son."]]},{de:"Tochter",art:"die",en:"daughter",lvl:"A1",phrases:[["Die Tochter spielt.","The daughter plays."],["Meine Tochter ist süß.","My daughter is sweet."]]},{de:"Großmutter",art:"die",en:"grandmother",lvl:"A1",phrases:[["Meine Großmutter ist alt.","My grandmother is old."],["Die Großmutter backt.","The grandmother bakes."]]},{de:"Großvater",art:"der",en:"grandfather",lvl:"A1",phrases:[["Mein Großvater liest.","My grandfather reads."],["Der Großvater erzählt.","The grandfather tells stories."]]},{de:"Onkel",art:"der",en:"uncle",lvl:"A1",phrases:[["Mein Onkel wohnt hier.","My uncle lives here."],["Der Onkel ist lustig.","The uncle is funny."]]},{de:"Tante",art:"die",en:"aunt",lvl:"A1",phrases:[["Meine Tante kocht gut.","My aunt cooks well."],["Die Tante besucht uns.","The aunt visits us."]]},{de:"Eltern",art:"die",en:"parents",lvl:"A1",phrases:[["Meine Eltern sind nett.","My parents are nice."],["Die Eltern helfen mir.","The parents help me."]]},{de:"Geschwister",art:"die",en:"siblings",lvl:"A2",phrases:[["Ich habe zwei Geschwister.","I have two siblings."],["Geschwister streiten oft.","Siblings often argue."]]},{de:"Ehemann",art:"der",en:"husband",lvl:"A2",phrases:[["Ihr Ehemann heißt Tom.","Her husband is called Tom."],["Mein Ehemann ist Arzt.","My husband is a doctor."]]},{de:"Ehefrau",art:"die",en:"wife",lvl:"A2",phrases:[["Seine Ehefrau lacht.","His wife laughs."],["Meine Ehefrau arbeitet.","My wife works."]]}],
  "Farben":[{de:"rot",art:null,en:"red",lvl:"A1",phrases:[["Das Auto ist rot.","The car is red."],["Ich mag Rot.","I like red."]]},{de:"blau",art:null,en:"blue",lvl:"A1",phrases:[["Der Himmel ist blau.","The sky is blue."],["Sie trägt Blau.","She wears blue."]]},{de:"grün",art:null,en:"green",lvl:"A1",phrases:[["Das Gras ist grün.","The grass is green."],["Grün ist meine Farbe.","Green is my colour."]]},{de:"gelb",art:null,en:"yellow",lvl:"A1",phrases:[["Die Sonne ist gelb.","The sun is yellow."],["Eine gelbe Blume.","A yellow flower."]]},{de:"schwarz",art:null,en:"black",lvl:"A1",phrases:[["Die Nacht ist schwarz.","The night is black."],["Er trägt Schwarz.","He wears black."]]},{de:"weiß",art:null,en:"white",lvl:"A1",phrases:[["Schnee ist weiß.","Snow is white."],["Ein weißes Hemd.","A white shirt."]]},{de:"grau",art:null,en:"grey",lvl:"A1",phrases:[["Der Himmel ist grau.","The sky is grey."],["Ein graues Auto.","A grey car."]]},{de:"braun",art:null,en:"brown",lvl:"A1",phrases:[["Der Tisch ist braun.","The table is brown."],["Braune Augen.","Brown eyes."]]},{de:"orange",art:null,en:"orange",lvl:"A1",phrases:[["Die Orange ist orange.","The orange is orange."],["Ein oranges Kleid.","An orange dress."]]},{de:"lila",art:null,en:"purple",lvl:"A1",phrases:[["Die Blume ist lila.","The flower is purple."],["Mein Lieblingsfarbe ist Lila.","My favourite colour is purple."]]},{de:"rosa",art:null,en:"pink",lvl:"A1",phrases:[["Das Kind mag Rosa.","The child likes pink."],["Ein rosa Hemd.","A pink shirt."]]}],
  "Zeit":[{de:"Montag",art:"der",en:"Monday",lvl:"A1",phrases:[["Montag ist der erste Tag.","Monday is the first day."],["Am Montag arbeite ich.","On Monday I work."]]},{de:"Dienstag",art:"der",en:"Tuesday",lvl:"A1",phrases:[["Dienstag habe ich Kurs.","Tuesday I have a course."],["Bis Dienstag!","See you Tuesday!"]]},{de:"Mittwoch",art:"der",en:"Wednesday",lvl:"A1",phrases:[["Am Mittwoch koche ich.","On Wednesday I cook."],["Jeden Mittwoch Sport.","Every Wednesday sport."]]},{de:"Donnerstag",art:"der",en:"Thursday",lvl:"A1",phrases:[["Donnerstag ist frei.","Thursday is free."],["Wir treffen uns Donnerstag.","We meet on Thursday."]]},{de:"Freitag",art:"der",en:"Friday",lvl:"A1",phrases:[["Freitag ist Wochenende.","Friday is the weekend."],["Am Freitag gehe ich aus.","On Friday I go out."]]},{de:"Samstag",art:"der",en:"Saturday",lvl:"A1",phrases:[["Samstag schlafe ich lang.","Saturday I sleep in."],["Am Samstag kaufe ich ein.","On Saturday I shop."]]},{de:"Sonntag",art:"der",en:"Sunday",lvl:"A1",phrases:[["Sonntag ist Ruhetag.","Sunday is a rest day."],["Am Sonntag bin ich ruhig.","On Sunday I am quiet."]]},{de:"Frühling",art:"der",en:"spring",lvl:"A1",phrases:[["Im Frühling blühen Blumen.","In spring flowers bloom."],["Der Frühling ist warm.","Spring is warm."]]},{de:"Sommer",art:"der",en:"summer",lvl:"A1",phrases:[["Im Sommer ist es heiß.","In summer it is hot."],["Ich liebe den Sommer.","I love summer."]]},{de:"Herbst",art:"der",en:"autumn",lvl:"A1",phrases:[["Im Herbst fallen Blätter.","In autumn leaves fall."],["Der Herbst ist kühl.","Autumn is cool."]]},{de:"Winter",art:"der",en:"winter",lvl:"A1",phrases:[["Im Winter schneit es.","In winter it snows."],["Der Winter ist kalt.","Winter is cold."]]},{de:"Uhrzeit",art:"die",en:"time",lvl:"A1",phrases:[["Wie spät ist es?","What time is it?"],["Die Uhrzeit ist acht.","The time is eight."]]},{de:"Datum",art:"das",en:"date",lvl:"A1",phrases:[["Was ist das Datum?","What is the date?"],["Das Datum ist der erste Mai.","The date is the first of May."]]},{de:"Stunde",art:"die",en:"hour",lvl:"A1",phrases:[["Eine Stunde dauert es.","It takes one hour."],["In einer Stunde bin ich da.","In one hour I am there."]]},{de:"Minute",art:"die",en:"minute",lvl:"A1",phrases:[["Ich komme in fünf Minuten.","I come in five minutes."],["Eine Minute, bitte!","One minute, please!"]]},{de:"Woche",art:"die",en:"week",lvl:"A1",phrases:[["Die Woche hat sieben Tage.","The week has seven days."],["Nächste Woche komme ich.","Next week I come."]]},{de:"Jahr",art:"das",en:"year",lvl:"A1",phrases:[["Das Jahr hat zwölf Monate.","The year has twelve months."],["Dieses Jahr war gut.","This year was good."]]},{de:"Morgen",art:"der",en:"morning",lvl:"A1",phrases:[["Der Morgen ist frisch.","The morning is fresh."],["Guten Morgen!","Good morning!"]]},{de:"Abend",art:"der",en:"evening",lvl:"A1",phrases:[["Der Abend ist ruhig.","The evening is quiet."],["Guten Abend!","Good evening!"]]}],
  "Berufe":[{de:"Koch",art:"der",en:"chef",lvl:"A2",phrases:[["Der Koch kocht gut.","The chef cooks well."],["Ich bin Koch.","I am a chef."]]},{de:"Kellner",art:"der",en:"waiter",lvl:"A2",phrases:[["Der Kellner bringt Wasser.","The waiter brings water."],["Der Kellner ist freundlich.","The waiter is friendly."]]},{de:"Verkäufer",art:"der",en:"salesperson",lvl:"A1",phrases:[["Der Verkäufer hilft mir.","The salesperson helps me."],["Sie ist Verkäuferin.","She is a saleswoman."]]},{de:"Fahrer",art:"der",en:"driver",lvl:"A2",phrases:[["Der Fahrer ist pünktlich.","The driver is on time."],["Er ist Fahrer von Beruf.","He is a driver by profession."]]},{de:"Friseur",art:"der",en:"hairdresser",lvl:"A2",phrases:[["Der Friseur schneidet Haare.","The hairdresser cuts hair."],["Ich gehe zum Friseur.","I go to the hairdresser."]]},{de:"Bäcker",art:"der",en:"baker",lvl:"A2",phrases:[["Der Bäcker backt Brot.","The baker bakes bread."],["Frisches Brot vom Bäcker.","Fresh bread from the baker."]]},{de:"Mechaniker",art:"der",en:"mechanic",lvl:"A2",phrases:[["Der Mechaniker repariert.","The mechanic repairs."],["Ich brauche einen Mechaniker.","I need a mechanic."]]},{de:"Krankenpfleger",art:"der",en:"nurse",lvl:"A2",phrases:[["Der Krankenpfleger hilft.","The nurse helps."],["Sie ist Krankenpflegerin.","She is a nurse."]]},{de:"Sekretärin",art:"die",en:"secretary",lvl:"A2",phrases:[["Die Sekretärin schreibt.","The secretary writes."],["Sie ist gute Sekretärin.","She is a good secretary."]]},{de:"Ingenieur",art:"der",en:"engineer",lvl:"A2",phrases:[["Der Ingenieur plant.","The engineer plans."],["Er ist Ingenieur.","He is an engineer."]]}],
  "Wohnen":[{de:"Wohnung",art:"die",en:"apartment",lvl:"A1",phrases:[["Die Wohnung ist groß.","The apartment is big."],["Ich suche eine Wohnung.","I look for an apartment."]]},{de:"Zimmer",art:"das",en:"room",lvl:"A1",phrases:[["Das Zimmer ist klein.","The room is small."],["Mein Zimmer ist oben.","My room is upstairs."]]},{de:"Haus",art:"das",en:"house",lvl:"A1",phrases:[["Das Haus ist alt.","The house is old."],["Wir haben ein Haus.","We have a house."]]},{de:"Küche",art:"die",en:"kitchen",lvl:"A1",phrases:[["Die Küche ist neu.","The kitchen is new."],["Ich koche in der Küche.","I cook in the kitchen."]]},{de:"Bett",art:"das",en:"bed",lvl:"A1",phrases:[["Das Bett ist weich.","The bed is soft."],["Ich gehe ins Bett.","I go to bed."]]},{de:"Tisch",art:"der",en:"table",lvl:"A1",phrases:[["Der Tisch ist rund.","The table is round."],["Das Buch ist auf dem Tisch.","The book is on the table."]]},{de:"Miete",art:"die",en:"rent",lvl:"A2",phrases:[["Die Miete ist teuer.","The rent is expensive."],["Ich zahle die Miete.","I pay the rent."]]},{de:"Möbel",art:"die",en:"furniture",lvl:"A2",phrases:[["Die Möbel sind neu.","The furniture is new."],["Wir kaufen Möbel.","We buy furniture."]]},{de:"Umzug",art:"der",en:"move",lvl:"A2",phrases:[["Der Umzug ist morgen.","The move is tomorrow."],["Ein Umzug ist anstrengend.","A move is tiring."]]},{de:"Nachbar",art:"der",en:"neighbor",lvl:"A2",phrases:[["Mein Nachbar ist laut.","My neighbor is loud."],["Der Nachbar hilft mir.","The neighbor helps me."]]},{de:"Schlafzimmer",art:"das",en:"bedroom",lvl:"A1",phrases:[["Das Schlafzimmer ist ruhig.","The bedroom is quiet."],["Mein Schlafzimmer ist klein.","My bedroom is small."]]},{de:"Badezimmer",art:"das",en:"bathroom",lvl:"A1",phrases:[["Das Badezimmer ist sauber.","The bathroom is clean."],["Ich bin im Badezimmer.","I am in the bathroom."]]}],
  "Umwelt":[{de:"Wetter",art:"das",en:"weather",lvl:"A1",phrases:[["Das Wetter ist schön.","The weather is nice."],["Wie ist das Wetter?","How is the weather?"]]},{de:"Sonne",art:"die",en:"sun",lvl:"A1",phrases:[["Die Sonne scheint.","The sun shines."],["Die Sonne ist warm.","The sun is warm."]]},{de:"Regen",art:"der",en:"rain",lvl:"A1",phrases:[["Der Regen ist kalt.","The rain is cold."],["Es gibt Regen.","There is rain."]]},{de:"Tier",art:"das",en:"animal",lvl:"A1",phrases:[["Das Tier ist groß.","The animal is big."],["Ich mag Tiere.","I like animals."]]},{de:"Baum",art:"der",en:"tree",lvl:"A1",phrases:[["Der Baum ist hoch.","The tree is tall."],["Da steht ein Baum.","There stands a tree."]]},{de:"Klima",art:"das",en:"climate",lvl:"A2",phrases:[["Das Klima ist warm.","The climate is warm."],["Das Klima ändert sich.","The climate changes."]]},{de:"Natur",art:"die",en:"nature",lvl:"A2",phrases:[["Die Natur ist schön.","Nature is beautiful."],["Ich liebe die Natur.","I love nature."]]},{de:"Müll",art:"der",en:"garbage",lvl:"A2",phrases:[["Der Müll ist voll.","The garbage is full."],["Ich bringe den Müll raus.","I take out the garbage."]]},{de:"Umwelt",art:"die",en:"environment",lvl:"A2",phrases:[["Die Umwelt ist wichtig.","The environment is important."],["Wir schützen die Umwelt.","We protect the environment."]]},{de:"Schnee",art:"der",en:"snow",lvl:"A1",phrases:[["Der Schnee ist weiß.","The snow is white."],["Es gibt Schnee.","There is snow."]]},{de:"Wind",art:"der",en:"wind",lvl:"A1",phrases:[["Der Wind ist stark.","The wind is strong."],["Es gibt viel Wind.","There is a lot of wind."]]}],
  "Reisen":[{de:"Reise",art:"die",en:"trip",lvl:"A1",phrases:[["Die Reise war lang.","The trip was long."],["Ich mache eine Reise.","I take a trip."]]},{de:"Zug",art:"der",en:"train",lvl:"A1",phrases:[["Der Zug ist spät.","The train is late."],["Ich fahre mit dem Zug.","I go by train."]]},{de:"Auto",art:"das",en:"car",lvl:"A1",phrases:[["Das Auto ist rot.","The car is red."],["Ich fahre Auto.","I drive a car."]]},{de:"Flugzeug",art:"das",en:"airplane",lvl:"A1",phrases:[["Das Flugzeug fliegt.","The airplane flies."],["Ich nehme das Flugzeug.","I take the airplane."]]},{de:"Bahnhof",art:"der",en:"train station",lvl:"A1",phrases:[["Wo ist der Bahnhof?","Where is the station?"],["Ich bin am Bahnhof.","I am at the station."]]},{de:"Ticket",art:"das",en:"ticket",lvl:"A1",phrases:[["Das Ticket ist teuer.","The ticket is expensive."],["Ich kaufe ein Ticket.","I buy a ticket."]]},{de:"Unterkunft",art:"die",en:"accommodation",lvl:"A2",phrases:[["Die Unterkunft ist gut.","The accommodation is good."],["Ich suche eine Unterkunft.","I look for accommodation."]]},{de:"Gepäck",art:"das",en:"luggage",lvl:"A2",phrases:[["Mein Gepäck ist schwer.","My luggage is heavy."],["Wo ist mein Gepäck?","Where is my luggage?"]]},{de:"Ausflug",art:"der",en:"excursion",lvl:"A2",phrases:[["Der Ausflug war schön.","The excursion was nice."],["Wir machen einen Ausflug.","We take an excursion."]]},{de:"Grenze",art:"die",en:"border",lvl:"A2",phrases:[["Die Grenze ist offen.","The border is open."],["Wir fahren über die Grenze.","We cross the border."]]},{de:"Bus",art:"der",en:"bus",lvl:"A1",phrases:[["Der Bus kommt gleich.","The bus comes soon."],["Ich fahre mit dem Bus.","I go by bus."]]},{de:"Flughafen",art:"der",en:"airport",lvl:"A1",phrases:[["Der Flughafen ist groß.","The airport is big."],["Wir sind am Flughafen.","We are at the airport."]]}],
  "Essen/Trinken":[{de:"Frühstück",art:"das",en:"breakfast",lvl:"A1",phrases:[["Das Frühstück ist fertig.","Breakfast is ready."],["Ich esse Frühstück.","I eat breakfast."]]},{de:"Wasser",art:"das",en:"water",lvl:"A1",phrases:[["Das Wasser ist kalt.","The water is cold."],["Ich trinke Wasser.","I drink water."]]},{de:"Brot",art:"das",en:"bread",lvl:"A1",phrases:[["Das Brot ist frisch.","The bread is fresh."],["Ich kaufe Brot.","I buy bread."]]},{de:"Kaffee",art:"der",en:"coffee",lvl:"A1",phrases:[["Der Kaffee ist heiß.","The coffee is hot."],["Ich trinke Kaffee.","I drink coffee."]]},{de:"Obst",art:"das",en:"fruit",lvl:"A1",phrases:[["Das Obst ist süß.","The fruit is sweet."],["Ich esse Obst.","I eat fruit."]]},{de:"Restaurant",art:"das",en:"restaurant",lvl:"A1",phrases:[["Das Restaurant ist voll.","The restaurant is full."],["Wir gehen ins Restaurant.","We go to the restaurant."]]},{de:"Getränk",art:"das",en:"drink",lvl:"A2",phrases:[["Das Getränk ist kalt.","The drink is cold."],["Was möchtest du trinken?","What would you like to drink?"]]},{de:"Mahlzeit",art:"die",en:"meal",lvl:"A2",phrases:[["Die Mahlzeit war lecker.","The meal was tasty."],["Eine Mahlzeit am Tag.","One meal a day."]]},{de:"Rezept",art:"das",en:"recipe",lvl:"A2",phrases:[["Das Rezept ist einfach.","The recipe is easy."],["Ich brauche ein Rezept.","I need a recipe."]]},{de:"Speisekarte",art:"die",en:"menu",lvl:"A2",phrases:[["Die Speisekarte ist lang.","The menu is long."],["Ich lese die Speisekarte.","I read the menu."]]},{de:"Mittagessen",art:"das",en:"lunch",lvl:"A1",phrases:[["Das Mittagessen ist fertig.","Lunch is ready."],["Was gibt es zum Mittagessen?","What is there for lunch?"]]},{de:"Abendessen",art:"das",en:"dinner",lvl:"A1",phrases:[["Das Abendessen war gut.","Dinner was good."],["Wir essen Abendessen.","We eat dinner."]]}],
  "Einkaufen":[{de:"Preis",art:"der",en:"price",lvl:"A1",phrases:[["Der Preis ist hoch.","The price is high."],["Was ist der Preis?","What is the price?"]]},{de:"Geld",art:"das",en:"money",lvl:"A1",phrases:[["Ich habe kein Geld.","I have no money."],["Das Geld ist weg.","The money is gone."]]},{de:"Geschäft",art:"das",en:"shop",lvl:"A1",phrases:[["Das Geschäft ist offen.","The shop is open."],["Ich gehe ins Geschäft.","I go to the shop."]]},{de:"Kleidung",art:"die",en:"clothing",lvl:"A1",phrases:[["Die Kleidung ist neu.","The clothing is new."],["Ich kaufe Kleidung.","I buy clothing."]]},{de:"Markt",art:"der",en:"market",lvl:"A1",phrases:[["Der Markt ist groß.","The market is big."],["Ich gehe zum Markt.","I go to the market."]]},{de:"Lebensmittel",art:"die",en:"groceries",lvl:"A2",phrases:[["Die Lebensmittel sind frisch.","The groceries are fresh."],["Ich kaufe Lebensmittel.","I buy groceries."]]},{de:"Rabatt",art:"der",en:"discount",lvl:"A2",phrases:[["Es gibt einen Rabatt.","There is a discount."],["Der Rabatt ist groß.","The discount is big."]]},{de:"Quittung",art:"die",en:"receipt",lvl:"A2",phrases:[["Hier ist die Quittung.","Here is the receipt."],["Ich brauche eine Quittung.","I need a receipt."]]},{de:"Größe",art:"die",en:"size",lvl:"A2",phrases:[["Welche Größe brauchst du?","What size do you need?"],["Die Größe passt.","The size fits."]]},{de:"Kasse",art:"die",en:"checkout",lvl:"A1",phrases:[["Ich gehe zur Kasse.","I go to the checkout."],["Die Kasse ist dort.","The checkout is there."]]}],
  "Dienstleistungen":[{de:"Post",art:"die",en:"post office",lvl:"A1",phrases:[["Die Post ist zu.","The post office is closed."],["Ich gehe zur Post.","I go to the post office."]]},{de:"Bank",art:"die",en:"bank",lvl:"A1",phrases:[["Die Bank ist nah.","The bank is near."],["Ich gehe zur Bank.","I go to the bank."]]},{de:"Polizei",art:"die",en:"police",lvl:"A1",phrases:[["Ich rufe die Polizei.","I call the police."],["Die Polizei kommt.","The police come."]]},{de:"Apotheke",art:"die",en:"pharmacy",lvl:"A1",phrases:[["Die Apotheke ist offen.","The pharmacy is open."],["Ich gehe zur Apotheke.","I go to the pharmacy."]]},{de:"Arzt",art:"der",en:"doctor",lvl:"A1",phrases:[["Der Arzt ist da.","The doctor is here."],["Ich gehe zum Arzt.","I go to the doctor."]]},{de:"Termin",art:"der",en:"appointment",lvl:"A2",phrases:[["Ich habe einen Termin.","I have an appointment."],["Der Termin ist morgen.","The appointment is tomorrow."]]},{de:"Versicherung",art:"die",en:"insurance",lvl:"A2",phrases:[["Die Versicherung zahlt.","The insurance pays."],["Ich brauche eine Versicherung.","I need insurance."]]},{de:"Rathaus",art:"das",en:"town hall",lvl:"A2",phrases:[["Das Rathaus ist alt.","The town hall is old."],["Ich gehe zum Rathaus.","I go to the town hall."]]},{de:"Amt",art:"das",en:"office (gov)",lvl:"A2",phrases:[["Das Amt ist geschlossen.","The office is closed."],["Ich war beim Amt.","I was at the office."]]},{de:"Krankenhaus",art:"das",en:"hospital",lvl:"A1",phrases:[["Das Krankenhaus ist groß.","The hospital is big."],["Er ist im Krankenhaus.","He is in the hospital."]]}],
  "Erziehung":[{de:"Schule",art:"die",en:"school",lvl:"A1",phrases:[["Die Schule beginnt.","School begins."],["Ich gehe zur Schule.","I go to school."]]},{de:"Buch",art:"das",en:"book",lvl:"A1",phrases:[["Das Buch ist gut.","The book is good."],["Ich lese ein Buch.","I read a book."]]},{de:"Lehrer",art:"der",en:"teacher",lvl:"A1",phrases:[["Der Lehrer ist nett.","The teacher is nice."],["Mein Lehrer hilft mir.","My teacher helps me."]]},{de:"Prüfung",art:"die",en:"exam",lvl:"A1",phrases:[["Die Prüfung ist schwer.","The exam is hard."],["Ich habe eine Prüfung.","I have an exam."]]},{de:"Sprache",art:"die",en:"language",lvl:"A1",phrases:[["Die Sprache ist schön.","The language is beautiful."],["Ich lerne eine Sprache.","I learn a language."]]},{de:"Universität",art:"die",en:"university",lvl:"A2",phrases:[["Die Universität ist groß.","The university is big."],["Ich studiere an der Universität.","I study at the university."]]},{de:"Kurs",art:"der",en:"course",lvl:"A2",phrases:[["Der Kurs ist interessant.","The course is interesting."],["Ich mache einen Kurs.","I take a course."]]},{de:"Note",art:"die",en:"grade",lvl:"A2",phrases:[["Die Note ist gut.","The grade is good."],["Ich habe eine gute Note.","I have a good grade."]]},{de:"Wissen",art:"das",en:"knowledge",lvl:"A2",phrases:[["Sein Wissen ist groß.","His knowledge is great."],["Wissen ist wichtig.","Knowledge is important."]]},{de:"Mathematik",art:"die",en:"mathematics",lvl:"A1",phrases:[["Mathematik ist schwer.","Mathematics is hard."],["Ich lerne Mathematik.","I learn mathematics."]]},{de:"Klasse",art:"die",en:"class",lvl:"A1",phrases:[["Die Klasse ist groß.","The class is big."],["Ich bin in Klasse fünf.","I am in class five."]]},{de:"Hausaufgabe",art:"die",en:"homework",lvl:"A1",phrases:[["Die Hausaufgabe ist fertig.","The homework is done."],["Ich mache Hausaufgaben.","I do homework."]]}],
  "Arbeit/Beruf":[{de:"Beruf",art:"der",en:"profession",lvl:"A1",phrases:[["Was ist dein Beruf?","What is your job?"],["Mein Beruf ist Lehrer.","My job is teacher."]]},{de:"Arbeit",art:"die",en:"work",lvl:"A1",phrases:[["Die Arbeit ist schwer.","The work is hard."],["Ich gehe zur Arbeit.","I go to work."]]},{de:"Büro",art:"das",en:"office",lvl:"A1",phrases:[["Das Büro ist groß.","The office is big."],["Ich bin im Büro.","I am in the office."]]},{de:"Chef",art:"der",en:"boss",lvl:"A1",phrases:[["Mein Chef ist nett.","My boss is nice."],["Der Chef kommt.","The boss comes."]]},{de:"Kollege",art:"der",en:"colleague",lvl:"A1",phrases:[["Mein Kollege hilft.","My colleague helps."],["Der Kollege ist neu.","The colleague is new."]]},{de:"Gehalt",art:"das",en:"salary",lvl:"A2",phrases:[["Mein Gehalt ist gut.","My salary is good."],["Das Gehalt kommt Freitag.","The salary comes Friday."]]},{de:"Bewerbung",art:"die",en:"application",lvl:"A2",phrases:[["Die Bewerbung ist fertig.","The application is ready."],["Ich schreibe eine Bewerbung.","I write an application."]]},{de:"Besprechung",art:"die",en:"meeting",lvl:"A2",phrases:[["Die Besprechung ist lang.","The meeting is long."],["Ich habe eine Besprechung.","I have a meeting."]]},{de:"Rente",art:"die",en:"pension",lvl:"A2",phrases:[["Die Rente ist niedrig.","The pension is low."],["Er ist in Rente.","He is retired."]]},{de:"Stelle",art:"die",en:"position/job",lvl:"A2",phrases:[["Ich suche eine Stelle.","I look for a job."],["Die Stelle ist frei.","The position is free."]]},{de:"Arbeitszeit",art:"die",en:"working hours",lvl:"A2",phrases:[["Die Arbeitszeit ist lang.","The working hours are long."],["Flexible Arbeitszeit.","Flexible working hours."]]}],
  "Freizeit":[{de:"Sport",art:"der",en:"sport",lvl:"A1",phrases:[["Sport macht Spaß.","Sport is fun."],["Ich treibe Sport.","I do sport."]]},{de:"Hobby",art:"das",en:"hobby",lvl:"A1",phrases:[["Was ist dein Hobby?","What is your hobby?"],["Mein Hobby ist Lesen.","My hobby is reading."]]},{de:"Musik",art:"die",en:"music",lvl:"A1",phrases:[["Die Musik ist laut.","The music is loud."],["Ich höre Musik.","I listen to music."]]},{de:"Kino",art:"das",en:"cinema",lvl:"A1",phrases:[["Das Kino ist nah.","The cinema is near."],["Ich gehe ins Kino.","I go to the cinema."]]},{de:"Spiel",art:"das",en:"game",lvl:"A1",phrases:[["Das Spiel ist toll.","The game is great."],["Wir spielen ein Spiel.","We play a game."]]},{de:"Internet",art:"das",en:"internet",lvl:"A1",phrases:[["Das Internet ist langsam.","The internet is slow."],["Ich nutze das Internet.","I use the internet."]]},{de:"Konzert",art:"das",en:"concert",lvl:"A2",phrases:[["Das Konzert war gut.","The concert was good."],["Ich gehe ins Konzert.","I go to the concert."]]},{de:"Verein",art:"der",en:"club",lvl:"A2",phrases:[["Der Verein ist groß.","The club is big."],["Ich bin im Verein.","I am in the club."]]},{de:"Ausstellung",art:"die",en:"exhibition",lvl:"A2",phrases:[["Die Ausstellung ist neu.","The exhibition is new."],["Wir besuchen die Ausstellung.","We visit the exhibition."]]},{de:"Urlaub",art:"der",en:"holiday",lvl:"A1",phrases:[["Der Urlaub war schön.","The holiday was nice."],["Ich mache Urlaub.","I am on holiday."]]},{de:"Fußball",art:"der",en:"football",lvl:"A1",phrases:[["Fußball macht Spaß.","Football is fun."],["Ich spiele Fußball.","I play football."]]}],
  "Körper/Gesundheit":[{de:"Kopf",art:"der",en:"head",lvl:"A1",phrases:[["Mein Kopf tut weh.","My head hurts."],["Der Kopf ist rund.","The head is round."]]},{de:"Hand",art:"die",en:"hand",lvl:"A1",phrases:[["Die Hand ist kalt.","The hand is cold."],["Gib mir die Hand.","Give me your hand."]]},{de:"Auge",art:"das",en:"eye",lvl:"A1",phrases:[["Das Auge ist blau.","The eye is blue."],["Mein Auge tut weh.","My eye hurts."]]},{de:"Krank",art:null,en:"sick",lvl:"A1",phrases:[["Ich bin krank.","I am sick."],["Er ist krank.","He is sick."]]},{de:"Schmerz",art:"der",en:"pain",lvl:"A2",phrases:[["Der Schmerz ist stark.","The pain is strong."],["Ich habe Schmerzen.","I have pain."]]},{de:"Medikament",art:"das",en:"medicine",lvl:"A2",phrases:[["Das Medikament hilft.","The medicine helps."],["Ich nehme ein Medikament.","I take medicine."]]},{de:"Gesundheit",art:"die",en:"health",lvl:"A2",phrases:[["Die Gesundheit ist wichtig.","Health is important."],["Auf deine Gesundheit!","To your health!"]]},{de:"Fieber",art:"das",en:"fever",lvl:"A2",phrases:[["Ich habe Fieber.","I have a fever."],["Das Fieber ist hoch.","The fever is high."]]},{de:"Müde",art:null,en:"tired",lvl:"A1",phrases:[["Ich bin müde.","I am tired."],["Er ist sehr müde.","He is very tired."]]}],
  "Verbindungswörter":[{de:"und",art:null,en:"and",lvl:"A1",phrases:[["Ich und du.","Me and you."],["Brot und Butter.","Bread and butter."]]},{de:"oder",art:null,en:"or",lvl:"A1",phrases:[["Tee oder Kaffee?","Tea or coffee?"],["Heute oder morgen?","Today or tomorrow?"]]},{de:"aber",art:null,en:"but",lvl:"A1",phrases:[["Klein aber fein.","Small but nice."],["Ich komme, aber spät.","I come, but late."]]},{de:"weil",art:null,en:"because",lvl:"A1",phrases:[["Ich bleibe, weil es regnet.","I stay because it rains."],["Weil ich müde bin.","Because I am tired."]]},{de:"denn",art:null,en:"because/for",lvl:"A2",phrases:[["Ich gehe, denn es ist spät.","I go, for it is late."],["Sie lacht, denn es ist lustig.","She laughs, for it is funny."]]},{de:"dass",art:null,en:"that",lvl:"A1",phrases:[["Ich weiß, dass du kommst.","I know that you come."],["Es ist gut, dass du hier bist.","It is good that you are here."]]},{de:"wenn",art:null,en:"if/when",lvl:"A1",phrases:[["Wenn es regnet, bleibe ich.","If it rains, I stay."],["Ruf an, wenn du kommst.","Call when you come."]]},{de:"deshalb",art:null,en:"therefore",lvl:"A2",phrases:[["Es regnet, deshalb bleibe ich.","It rains, therefore I stay."],["Ich bin krank, deshalb gehe ich nicht.","I am sick, therefore I don't go."]]},{de:"trotzdem",art:null,en:"nevertheless",lvl:"A2",phrases:[["Es regnet. Trotzdem gehe ich.","It rains. Nevertheless I go."],["Müde, aber trotzdem glücklich.","Tired, but nevertheless happy."]]},{de:"obwohl",art:null,en:"although",lvl:"A2",phrases:[["Obwohl es regnet, gehe ich.","Although it rains, I go."],["Er lacht, obwohl er traurig ist.","He laughs although he is sad."]]},{de:"also",art:null,en:"so/thus",lvl:"A1",phrases:[["Es ist spät, also gehe ich.","It is late, so I go."],["Du kommst, also warte ich.","You come, so I wait."]]},{de:"dann",art:null,en:"then",lvl:"A1",phrases:[["Erst esse ich, dann gehe ich.","First I eat, then I go."],["Und was dann?","And what then?"]]}]
};

// ── XP / LEVELS ──────────────────────────────────────
// ── LESEN TEXTS (Reading comprehension — Goethe A2 exam style) ──────────────
const LESEN_TEXTS = [
  {
    id:'l1', lvl:'A1', title:'Meine Familie',
    text:'Ich heiße Anna und bin 30 Jahre alt. Ich wohne in Berlin mit meiner Familie. Mein Mann heißt Peter und arbeitet als Lehrer. Wir haben zwei Kinder: einen Sohn (Tom, 5 Jahre) und eine Tochter (Lisa, 8 Jahre). Meine Mutter wohnt auch in Berlin, aber mein Vater lebt in München. Am Wochenende besuchen wir oft meine Eltern.',
    questions:[
      {q:'Wie viele Kinder hat Anna?',opts:['Eines','Zwei','Drei'],ans:1},
      {q:'Was macht Peters Beruf?',opts:['Er ist Arzt.','Er ist Lehrer.','Er ist Fahrer.'],ans:1},
      {q:'Wo wohnt Annas Mutter?',opts:['In München','In Hamburg','In Berlin'],ans:2},
    ]
  },
  {
    id:'l2', lvl:'A1', title:'Das Café Central',
    text:'Café Central – Öffnungszeiten\nMontag bis Freitag: 8:00 – 18:00 Uhr\nSamstag: 9:00 – 16:00 Uhr\nSonntag: geschlossen\n\nWir bieten: Kaffee, Tee, Kuchen, Sandwiches und Suppen. Frühstück gibt es bis 11:00 Uhr. Mittagessen von 12:00 bis 14:00 Uhr. Kinder bis 6 Jahre essen kostenlos! WLAN gratis für alle Gäste.',
    questions:[
      {q:'Wann ist das Café am Sonntag geöffnet?',opts:['9:00 – 16:00','8:00 – 18:00','Nicht geöffnet'],ans:2},
      {q:'Bis wann gibt es Frühstück?',opts:['Bis 11:00 Uhr','Bis 12:00 Uhr','Bis 14:00 Uhr'],ans:0},
      {q:'Wer isst kostenlos?',opts:['Alle Kinder','Kinder bis 6 Jahre','Kinder bis 10 Jahre'],ans:1},
    ]
  },
  {
      id:'l3', lvl:'A2', title:'Der neue Job',
    text:'Lena Hoffmann hat lange nach einer Stelle gesucht. Sie hat Wirtschaft studiert und wollte eigentlich in einer großen Firma arbeiten. Aber nach vielen Bewerbungen hat sie schließlich eine Stelle in einem kleinen Familienbetrieb in Köln gefunden. Zuerst war sie enttäuscht, weil sie sich etwas anderes vorgestellt hatte. Doch schon nach wenigen Wochen hat sie gemerkt, dass ihr die Arbeit dort sehr gut gefällt. Ihr Chef lässt ihr viel Freiheit bei der Arbeit, und die Kollegen sind hilfsbereit. Das Gehalt ist zwar nicht so hoch wie in einer großen Firma, aber Lena sagt, sie würde die Stelle nicht mehr tauschen wollen.',
    questions:[
      {q:'Was hat Lena studiert?',opts:['Medizin','Wirtschaft','Informatik'],ans:1},
      {q:'Warum war Lena am Anfang enttäuscht?',opts:['Weil das Gehalt zu niedrig war.','Weil die Kollegen unfreundlich waren.','Weil sie sich eine andere Stelle vorgestellt hatte.'],ans:2},
      {q:'Was schätzt Lena an ihrer neuen Stelle besonders?',opts:['Das hohe Gehalt und die guten Arbeitszeiten.','Die Freiheit bei der Arbeit und die netten Kollegen.','Die Nähe zu ihrer Familie in Köln.'],ans:1},
      {q:'Was denkt Lena heute über ihren Job?',opts:['Sie sucht immer noch nach etwas Besserem.','Sie möchte bald in eine große Firma wechseln.','Sie ist zufrieden und möchte bleiben.'],ans:2},
    ]
  },
  {
    id:'l4', lvl:'A2', title:'Umzug in eine neue Stadt',
    text:'Jonas Weber ist vor sechs Monaten von München nach Hamburg gezogen, weil seine Freundin dort eine Stelle als Ärztin bekommen hat. Den Umzug hat er lange geplant, aber trotzdem war der Anfang schwer. In München hatte er viele Freunde und einen Job, den er mochte. In Hamburg musste er von vorne anfangen. Er hat sich zunächst sehr allein gefühlt, besonders weil er niemanden kannte. Nach drei Monaten hat er aber durch einen Sportverein neue Leute kennengelernt. Inzwischen gefällt ihm Hamburg gut, obwohl er München noch manchmal vermisst. Er hat auch eine neue Stelle als Grafiker gefunden und sagt, die Stadt habe ihn positiv überrascht.',
    questions:[
      {q:'Warum ist Jonas nach Hamburg gezogen?',opts:['Er hat dort einen besseren Job gefunden.','Seine Freundin hat dort eine Stelle bekommen.','Er wollte schon immer in Hamburg leben.'],ans:1},
      {q:'Was war für Jonas in den ersten Monaten am schwersten?',opts:['Er hat keine Wohnung gefunden.','Er hat seine Stelle in München verloren.','Er kannte niemanden in der neuen Stadt.'],ans:2},
      {q:'Wie hat Jonas neue Freunde in Hamburg gefunden?',opts:['Durch seine Arbeit als Grafiker.','Durch einen Sportverein.','Durch die Freunde seiner Freundin.'],ans:1},
      {q:'Was stimmt über Jonas heute?',opts:['Er denkt darüber nach, wieder nach München zu ziehen.','Er vermisst München nie.','Er hat Arbeit gefunden und fühlt sich wohler.'],ans:2},
    ]
  },
  {
    id:'l5', lvl:'A2', title:'Der Tauschmarkt',
    text:'Seit zwei Jahren organisiert Marta Blum jeden ersten Samstag im Monat einen Tauschmarkt in ihrem Stadtteil. Die Idee hatte sie, weil sie einmal einen alten Kinderwagen verschenken wollte und niemanden kannte, der ihn gebrauchen konnte. Auf dem Markt kann man Dinge mitbringen, die man nicht mehr braucht, und sie gegen andere Sachen tauschen oder einfach verschenken. Es gibt keine Preise – alles ist kostenlos. Marta hat festgestellt, dass besonders Kleidung, Bücher und Küchengeräte sehr gefragt sind. Inzwischen kommen jeden Monat zwischen 80 und 150 Personen. Marta freut sich, dass der Markt so beliebt geworden ist, aber sie sagt auch, dass die Organisation viel Zeit kostet.',
    questions:[
      {q:'Warum hat Marta den Tauschmarkt gegründet?',opts:['Weil sie Geld verdienen wollte.','Weil sie einen alten Kinderwagen loswerden wollte und keine Möglichkeit fand.','Weil die Stadt sie darum gebeten hat.'],ans:1},
      {q:'Was kann man auf dem Tauschmarkt machen?',opts:['Nur kaufen und verkaufen.','Dinge tauschen oder verschenken, ohne zu bezahlen.','Neue Produkte von lokalen Firmen kaufen.'],ans:1},
      {q:'Was wird auf dem Markt am meisten nachgefragt?',opts:['Möbel, Fahrräder und Spielzeug.','Elektronik und Sportartikel.','Kleidung, Bücher und Küchengeräte.'],ans:2},
      {q:'Was findet Marta an der Organisation schwierig?',opts:['Die Leute kommen nicht regelmäßig.','Es kostet sehr viel Zeit.','Es ist schwer, einen guten Ort zu finden.'],ans:1},
    ]
  },
  {
    id:'l6', lvl:'A2', title:'Brieffreundschaft über Grenzen',
    text:'Als Kind hatte Fatima Yildiz eine Brieffreundschaft mit einem Mädchen aus Frankreich. Die beiden haben sich über ihre Schule, ihre Hobbys und ihre Familien geschrieben. Irgendwann haben sie aufgehört, weil das Leben immer voller wurde. Vor einem Jahr hat Fatima durch Zufall eine alte Brief-Box gefunden und darin alle Briefe wiederentdeckt. Sie hat ihrer alten Freundin Claire eine E-Mail geschickt – und Claire hat sofort geantwortet. Heute schreiben sie sich regelmäßig, aber diesmal auf Englisch, weil Fatimas Französisch eingerostet ist und Claires Deutsch nie gut war. Letzten Sommer haben sie sich zum ersten Mal seit 25 Jahren persönlich getroffen. Fatima sagt, es war, als ob die Zeit gar nicht vergangen wäre.',
    questions:[
      {q:'Warum haben Fatima und Claire als Kinder aufgehört zu schreiben?',opts:['Weil sie sich gestritten haben.','Weil sie keine Zeit mehr hatten.','Weil die Post zu teuer wurde.'],ans:1},
      {q:'Wie hat Fatima den Kontakt wiederhergestellt?',opts:['Sie hat Claire auf einer Reise nach Frankreich getroffen.','Sie hat eine alte Brief-Box gefunden und Claire eine E-Mail geschickt.','Sie hat Claires Adresse über das Internet gesucht.'],ans:1},
      {q:'In welcher Sprache schreiben sich die beiden heute?',opts:['Auf Deutsch, weil Claire gut Deutsch spricht.','Auf Französisch, weil Fatima es noch immer kann.','Auf Englisch, weil keine von beiden die Sprache der anderen gut beherrscht.'],ans:2},
      {q:'Was sagt Fatima über das Wiedersehen nach 25 Jahren?',opts:['Es war seltsam, weil sie sich kaum wiedererkannt haben.','Es fühlte sich an, als wäre keine Zeit vergangen.','Sie waren beide enttäuscht, weil die Freundschaft sich verändert hatte.'],ans:1},
    ]
  },
];
